### ISSUE TITLE
[Discuss] View 내부 UI Component의 디자인 설정 순서

### ISSUE THREAD

**Issue by JaewoongLee-swift** [OFFTORIVER/BJGG#184]
**Issue : Discuss**
View 내부 UI Component의 디자인 설정 순서 논의

**Description**
View 내부 UI Component의 디자인 설정 순서를 어떻게 설정할지 논의가 필요합니다.
현재 각 View는 configureStyle 메소드를 통해 해당 View의 디자인 관련 설정을 관리하고 있습니다. 그렇다면 configureStyle 메소드에서 해당 View의 디자인 설정뿐만 아니라 내부 UI Component(UILabel, UIButton 등)의 디자인 설정도 관리하는게 더 유용할지 고민됩니다.
(기존의 View 내부 UI Component는 변수로 선언될 때 클로저로 선언해 클로저 내부에서 기본 설정을 진행하는 방식으로 선언하였습니다.)

```swift
// (1) configureStyle을 통한 UI Component 디자인 설정 관리
    private func configureStyle() {
        ...
        namelabel.font = .bbajiFont(.body1)
        namelabel.textColor = .bbagaGray2
        ...
    }

// (2) UI 선언 시 클로저를 통한 디자인 설정관리
    private lazy var nameLabel: UILabel = {
        let label = UILabel()
        label.font = .bbajiFont(.body1)
        label.textColor = .bbagaGray2
        
        return label
    }()
```

**Reference(Optional)**
아래의 PR을 통해 논의가 시작되었습니다.
PR : #181

**Comment by jeong-hyeonHwang** [comment]
2번 항목을 따른다.
`configureStyle`, `configureComponent` 내부에서 호출하던 요소를 클로저로 호출한다.
