### ISSUE TITLE
[Discuss] View 선언방식에 대한 논의

### ISSUE THREAD

**Issue by JaewoongLee-swift** [OFFTORIVER/BJGG#185]
**Issue : Discuss**
View 선언방식에 대한 논의

**Description**
현재 프로젝트에서 View를 선언할 때 let, var, lazy var 상관없이 선언되어 왔습니다.현재로썬 let이든 lazy var이든 문제가 발생하진 않지만 addTarget 같은 objective-C 코드와 함께 let 변수의 View가 사용될 경우 클래스 내의 선언 순서에 문제가 생겨 objective-C 코드로 된 메소드 실행에 버그가 발생할 여지가 있습니다. 이부분은 어떻게 관리하면 좋을지 논의해보면 좋을것 같습니다.

**Reference(Optional)**
해당 논의는 아래의 PR을 통해 시작되었습니다.
PR : #181

**Comment by jeong-hyeonHwang** [comment]
lazy var : 변하는 컴포넌트들
let : 변하지 않는 컴포넌트들
